DEFAULT_WINDOW_MS = 256.0
DEFAULT_OVERLAP_MS = 0
DEFAULT_NOTCH_HZ = 50
DEFAULT_LOWER_HZ = 0.1
DEFAULT_UPPER_HZ = 500
DEFAULT_RECORDING_LENGTH_S = 5
DEFAULT_USE_AUTO_SEGMENTATION = True
DEFAULT_APPLY_NORMALISATION = True
